### ISSUE TITLE
Ideas for boilerplate reduction

### ISSUE THREAD

**Issue by j-rock** [hyperium/tonic#1229]
### Crates

tonic-build

### Motivation

First and foremost, the `tonic` family is very well crafted, sensible, and I have thoroughly enjoyed playing around with these crates. I'd like to thank the contributors (esp. Lucio) for all the hard work - and I'd like to commend the clean design.

I am encountering two boilerplate paper cuts which I think can be eliminated with some good ole-fashioned code-gen:

#### 1. Structs implementing the generated "service" trait must be manually wrapped in generated Server structs.

For example, borrowing from examples/src/helloworld/server.rs

```rust
async fn main() -> Result<(), ...> {
    let greeter = MyGreeter::default();
    Server::builder()
        // It would be nice if we could directly pass |greeter| here and let
        // the |add_service| method take care of wrapping it into a GreeterServer.
        .add_service(GreeterServer::new(greeter))
        .serve(addr)
        .await?;
    ....
}
```

#### 2. To make use of tonic-reflection, one must manually import/plumb encoded FileDescriptorSet bytes.

```rust
// This is a lot of boilerplate
mod pb {
    pub const DESCRIPTOR_BYTES: &[u8] = tonic::include_file_descriptor_set!("helloworld");    
}

fn setup() {
   let mut refl_builder = tonic_reflection::server::Builder::configure();
   for server in servers {
     refl_builder = refl_builder.register_encoded_file_descriptor_set(
       // acquire relevant |DESCRIPTOR_BYTES|
     );
   }
   // Build/Attach reflection server
   // e.g. Server::builder().add_service(refl_builder.build()?)
}
```

To address both (1) and (2) in my own needs, I end up doing something like:

```rust
mod pb {
    pub const DESCRIPTOR_BYTES: &[u8] = tonic::include_file_descriptor_set!("helloworld");    
}

impl project::grpc_server::GrpcService for MyGreeter {
    type Service = greeter_server::GreeterServer<Self>;
    
    fn to_tonic_service(self) -> Self::Service { Self::Service::new(self) }
    fn encoded_descriptor() -> &'static [u8] { pb::DESCRIPTOR_BYTES }
}

impl GreeterService for MyGreeter {
    async fn say_hello(&self, request: Request<HelloRequest>) -> Result<Response<HelloReply>, Status> { ... }
}
```

### Proposal

1. It would be great if there was some code-generated trait to take something that implements the Service trait and to automatically wrap it into the generated Server struct when adding to a `tonic::transport::Server`.
2. It would be great if FileDescriptorSet/encoded_bytes entities could optionally be compiled into the `service.rs`.

I am open to ideas! I am open to help!

### Alternatives

I could, of course, write my own macro_rules block to minimize my woes. But I wonder if other users are feeling similar pain.

**Comment by LucioFranco** [comment]
> It would be great if there was some code-generated trait to take something that implements the Service trait and to automatically wrap it into the generated Server struct when adding to a tonic::transport::Server.

I think adding more traits will actually make this more complicated. We need the greeter service so that your trait implementation for the handler matches the generic bounds required by the server. I think going with traits and blanket impls will actually make this much more confusing and harder to debug

> It would be great if FileDescriptorSet/encoded_bytes entities could optionally be compiled into the service.rs.

So while I think this does somewhat present a better experience, not all users provide the file descriptor set. I think the current approach provides the best balance. In addition, you add an additional trait and I actually am in the boat of less traits the better. So only using the require set of traits will provide less paper cuts imo.

I appreciate the feedback, I do think there is space to improve the filedescriptor set but beyond our current approach it seems quite hard to achieve with the current features rust provides. Thanks for the proposal though! ❤️

**Comment by j-rock** [comment]
Thank you for weighing in!
