### ISSUE TITLE
When tonic is expected to become production ready?

### ISSUE THREAD

**Issue by dtoubelis** [hyperium/tonic#1432]
I came across this project while searching for a suitable gRPC implementation for a project. It seems that tonic is a good candidate for it but according to semver - it is not production ready. My question is if there is a timeline for the project to mature for production use?

**Comment by LucioFranco** [comment]
It is production ready and has been extremely battle tested. The reason it has not reached 1.0 is due to api's potentially changing for libraries that we expose/depend on and also I have not put the time into cleaning things up for a 1.0. That said, the current code is quite solid and is being used in many production use cases.
