### ISSUE TITLE
Passing rustls config to tonic server and client

### ISSUE THREAD

**Issue by hex1c** [hyperium/tonic#1615]
### Crates
tonic crate

### Motivation

Greetings! I am presently exploring certificate rotation and dynamic certificate resolution with `tonic`. The current approach I've adopted involves replicating the [example](https://github.com/hyperium/tonic/blob/master/examples/src/tls_rustls/server.rs), necessitating the inclusion of the same boilerplate as in the Tonic implementation. This would also address #1569 

### Proposal

Considering that `tonic` utilizes `rustls` as the TLS library, it would be advantageous to have an API for passing **ServerConfig** and **ClientConfig** in the ServerTlsConfig and **ClientTlsConfig** under the `tls` feature flag. This proposal suggests avoiding the addition of more fields to it. Implementation of the requested API would be contingent on Rustls. I am eager to receive your feedback on this idea and, if it meets your satisfaction, would be happy to proceed with a PR.

**Comment by LucioFranco** [comment]
Tonic on purpose does not expose the public API of rustls and thus it was remove due to this so that we do not have to tie ourselves to that. This is why if you want something more complicated like this I recommend following that example that you have there.

Tonic is going to eventually be moving away from providing TLS in the main crate, so this will likely not be a thing moving forward anyways. There are a couple options but its a bit hard to find who is the right person to maintain the tls adapter. Something we can maybe discuss in the future with @djc . For now I am going to close this issue since this has been discussed before.

**Comment by djc** [comment]
Would be happy to be involved in a discussion about the right way to customize TLS.

**Comment by LucioFranco** [comment]
Nothing yet, I have not made much progress on this.
