### ISSUE TITLE
Conditionaly adding services to router

### ISSUE THREAD

**Issue by hlb8122** [hyperium/tonic#265]
### Motivation

I have a server which will enjoy up to 5 different services, each of which should be able to be enable/disabled at boot time. Currently there seems to be no way to do this without 2^5 different branches.

### Proposal

Diesel has a similar problem when conditionally constructing queries, their solution is to provide a [into_boxed()](https://docs.diesel.rs/diesel/query_builder/struct.UpdateStatement.html#method.into_boxed) method.

A similar method could be added to [Router](https://docs.rs/tonic/0.1.1/tonic/transport/server/struct.Router.html).

A subsequent problem is that there is no way to generate a router with no services from a `Server` - this would also be required to conditionally add services. This could be done via a into_router() method on the [Server](https://docs.rs/tonic/0.1.1/tonic/transport/server/struct.Server.html).

The potential drawbacks here are that doing this may have unintended overhead due to the required boxing?

**Comment by LucioFranco** [comment]
So I unfortunately think this is not possible right now due to our https://docs.rs/tonic/0.1.1/tonic/transport/trait.NamedService.html#associatedconstant.NAME trait since it contains a const type. This makes it hard to implement `Either` for services. We also can't do the same for a trait object since the type system relies upon knowing the type to generate the correct path check.

So to implement this we would need to make a breaking change. So I'm curious if maybe using a macro could help here? If you end up running into many branches you may wan to use another type of router than the one tonic provides.

**Comment by hlb8122** [comment]
@LucioFranco I think a macro would be great substitute as long as n isn't too large.

Wondering about another possibility:
Instead of conditionally adding a service X you conditionally switch X out for an "empty service" with the same signature which always returns unavailable (or whatever is appropriate). Does that sound feasible?

**Comment by LucioFranco** [comment]
I am not sure that will work but I'd be open to a PR for that!
