### ISSUE TITLE
tonic_build::prost::Builder proto_path function panics 

### ISSUE THREAD

**Issue by petratbtl** [hyperium/tonic#357]
### Version

tonic-build = "0.2.0"
tonic = "0.2.1"
prost = "0.6"

### Platform

Linux R1 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Crates

tonic-build

### Description

I added the following code in build.rs:
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(false)
        .out_dir("proto/generated/")
        .proto_path("../proto/generated")
        .compile(&["proto/service.proto"], &["proto/"])?;

    Ok(())
}
```

I expected that I will be able to use the package "service" in following way in main.rs:
```
mod service {
    tonic::include_proto!("service");
}
```
Instead, the build failed with the following message:
```
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected identifier")', src/libcore/result.rs:1165:5
```

Build, and everything else works if I'm not using proto_path() in Builder, but then I can't use include_proto! (I have to use include! instead).
Bug is probably somewhere in the Builder in compiling protos using proto_path(); or maybe I'm using it wrong.

**Comment by LucioFranco** [comment]
Would you be able to show me what your proto looks like? (sorry for the late reply been on vacation)

**Comment by ajguerrer** [comment]
@petratbtl  Using [out_dir](https://docs.rs/tonic-build/0.2.0/tonic_build/struct.Builder.html#method.out_dir) will generate the proto files outside of [OUT_DIR](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), so you will need to follow the advice [here](https://docs.rs/tonic/0.2.1/tonic/macro.include_proto.html#note) and use `include!`.

**Comment by petratbtl** [comment]
@LucioFranco I was on the vacation, too, I'll find proto and paste it here. @ajguerrer tried that also, works but only if I comment out the line with proto_path.

**Comment by petratbtl** [comment]
> Would you be able to show me what your proto looks like? (sorry for the late reply been on vacation)

```
syntax = "proto3";

package service.proto;


service Greeter {
    // Sends a greeting
    rpc SayHello (HelloRequest) returns (HelloReply) {}
  }
  
  // The request message containing the user's name.
  message HelloRequest {
    string name = 1;
  }
  
  // The response message containing the greetings
  message HelloReply {
    string message = 1;
  }
```

**Comment by ajguerrer** [comment]
@petratbtl I think [proto_path](https://docs.rs/tonic-build/0.2.0/tonic_build/struct.Builder.html#method.proto_path) is for situations in which the messages are in a separate location from the service that makes use of them. 

Suppose the generated messages are output to some other module (or crate) `messages::hello`. Then you might need to generate the service with `.proto_path("messages::hello")` so that the messages can be found within the generated service code.

For your purposes, I don't think `proto_path` is necessary. If you ever end up using it, then the path arguments should be module path syntax, not file path syntax. 

I just started looking at tonic, so I'm a little unsure if that's how this feature was intended to be used but I'm sure @LucioFranco can clear up my mistakes if needed.

**Comment by LucioFranco** [comment]
Yup, that is correct, it is to be used to point to a different _module_ path where structs with the correct names exist.

**Comment by petratbtl** [comment]
@LucioFranco  & @ajguerrer  thanks for explanation and help! I'll close the issue.
