### ISSUE TITLE
Mention tower-http's logging/tracing middleware in the interceptor docs

### ISSUE THREAD

**Issue by davidpdrsn** [hyperium/tonic#654]
Several people are wondering if interceptors is the correct place to add logging, which it isn't since they cannot access the response. Instead once tower-http is released we should guide people towards its `Trace` middleware which supports gRPC out of the box as the recommended way to setup logging.

**Comment by scirner22** [comment]
Awesome! Thanks for the example.

**Comment by kalzoo** [comment]
Was very happy to find this, but unfortunately [regressions](https://github.com/tokio-rs/prost/issues/507) in `prost==0.8.0` means that it's unusable for me (and likely many others) until those are fixed, and because `tonic` has upgraded to that version of `prost`, we're stuck on `tonic==0.4.3`. Just FYI.

**Comment by davidpdrsn** [comment]
That regression isn't related to tracing, middleware or interceptors. The middleware can also be used with tonic 0.4 as shown here https://github.com/tower-rs/tower-http/blob/master/examples/tonic-key-value-store/src/main.rs
