### ISSUE TITLE
Add readme rustdoc tests to CI

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#68]
# Motivation

Ensure the readme code compiles and is up to date.

# Solution

I think we can call rustdoc directly and test the readme in its own CI stage.

**Comment by senden9** [comment]
Alternative Idea: Use [cargo-readme](https://github.com/livioribeiro/cargo-readme) to auto-generate / check the readme.
This way the README file would be in sync with the tonic docs.rs page. Code examples would be tested automatically via `cargo test` because the live in a `.rs` file.

Bonus: You have the same nice "introduction information" no mater if new users land on the docs.rs page or this GitHub repository.

**Comment by LucioFranco** [comment]
@senden9 the issue with that is we can't have fully-fledged examples in the main readme because it requires codegen and hooking into the rustdocs build.rs. I am considering just dropping examples from the readme since this will be hard and just point people to the examples crate.

**Comment by RetWolf** [comment]
@LucioFranco Is there currently any testing around the examples to ensure they are working? If not, is this something we should think about writing and adding into the CI?

**Comment by LucioFranco** [comment]
So I am going to remove all examples from the readme. We will instead point to the examples crate which is checked via CI already. All doc examples are also checked via CI and `cargo test`.

**Comment by RetWolf** [comment]
Sounds good!

**Comment by LucioFranco** [comment]
This can be closed now that we've removed examples from the readme, thanks for all the help!
