### ISSUE TITLE
Combine Tonic with Actix-web

### ISSUE THREAD

**Issue by Leanerz** [hyperium/tonic#690]
Hi

Is there a way to combine properly Tonic and Actix-web?

The goal is to get a GRPC client as pool and pass it to actix-web to use it, or even make a shared GRPC client without opening each time connection for each requests of users.

Any idea please to follow?

Thank you !

**Comment by davidpdrsn** [comment]
Hm not quite sure what you're asking. It should be possible to create a tonic client, the way you always do it, and somehow pass it to your actix-web app. Maybe using [`App::data`](https://docs.rs/actix-web/3.3.2/actix_web/struct.App.html#method.data)? I'm not experienced actix-web myself so I really don't know.

@Leanerz does that help? Otherwise, could you try and be more specific? Perhaps share some code?

**Comment by gold-wallet** [comment]
> Hm not quite sure what you're asking. It should be possible to create a tonic client, the way you always do it, and somehow pass it to your actix-web app. Maybe using [`App::data`](https://docs.rs/actix-web/3.3.2/actix_web/struct.App.html#method.data)? I'm not experienced actix-web myself so I really don't know.
> 
> @Leanerz does that help? Otherwise, could you try and be more specific? Perhaps share some code?

Does tonic support pooling? He asks to pass a pool instead of simple client.

**Comment by davidpdrsn** [comment]
A tonic client is backed by a [`tonic::transport::Channel`](https://docs.rs/tonic/0.4.3/tonic/transport/channel/struct.Channel.html) which by default establishes a single h2 connection to the host. Because of h2 you can send multiple requests in parallel (thanks to multiplexing) and clients can be shared by cloning them. Cloning is cheap and the underlying connection is reused. But it doesn't maintain a pool of multiple connections to the same host similar to what [`hyper::Client`](https://docs.rs/hyper/0.14.9/hyper/client/struct.Client.html) does.

You can however load balance across multiple endpoints using [`Channel::balance_list`](https://docs.rs/tonic/0.4.3/tonic/transport/channel/struct.Channel.html#method.balance_list).
