### ISSUE TITLE
Missing `grpc-status` header

### ISSUE THREAD

**Issue by tzilist** [hyperium/tonic#855]
I am currently trying to write a tower middleware that will pull the status of the grpc response from a tonic server. It looks like the header grpc-status is missing and I am unsure of how to make this happen without it. Is it possible to get the status code from the raw hyper response?

**Comment by davidpdrsn** [comment]
There are a few scenarios:

1. Your RPC returns `Err(status)`: Then `grpc-status` will be a header on the response.
2. Your RPC is unary (not a stream) and returns `Ok(msg)`: Then `grpc-status` will be a header on the [trailers](https://docs.rs/http-body/0.4.4/http_body/trait.Body.html#tymethod.poll_trailers). This is because unary responses are actually streams with a single item.
3. Your RPC is a stream: Then `grpc-status` is also in the [trailers](https://docs.rs/http-body/0.4.4/http_body/trait.Body.html#tymethod.poll_trailers).

This is basically just how gRPC works so this isn't tonic specific.

I'm curious about your use case. If you're looking for logging then I can recommend [`TraceLayer`](https://docs.rs/tower-http/latest/tower_http/trace/index.html) from `tower-http` which supports gRPC out of the box with `TraceLayer::new_for_grpc()`. There an complete tonic example [here](https://github.com/tower-rs/tower-http/blob/master/examples/tonic-key-value-store/src/main.rs#L175-L197).

**Comment by tzilist** [comment]
@davidpdrsn thank you for your response. We are indeed trying to make a logging layer, however, there are a few special things we need to handle that unfortunately makes `TraceLayer` unfeasible for our use case. If I am creating a tower service, what would be the correct way to call `poll_trailers` a tower service?

**Comment by davidpdrsn** [comment]
It requires a bit of wrapping. You make some `tower::Service` that wraps another `tower::Service`, that returns a future that wraps the inner service's future, the future returns a `http::Response` who's body wraps the inner service's response's body. Sounds more complicated than it is hopefully 😜

I'd recommend looking at how `tower_http::trace::Trace` is implemented starting with [its `Service` implementation](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/trace/service.rs#L301-L324).

**Comment by tzilist** [comment]
Ah ok I see! Thank you for your help! I'll close out this issue for now since there really isn't anything to be done on the tonic side of things :) Thanks for your help!
